### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by jozogs** [Medic01/Sustav_za_transfuziologiju#34]

**Comment by AntonioPavkovic** [comment]
While working on this Issue, I have noticed that there are some unused variables/funcitons/imports.
Should I open a new github issue or I can fix it in this one?

**Comment by jozogs** [comment]
> While working on this Issue, I have noticed that there are some unused variables/funcitons/imports. Should I open a new github issue or I can fix it in this one?

Nice catch, please sort it out on this one. Let's do it by `The Boy Scout Rule` (Always leave the code you are working on a little bit better than you found it.)
