### ISSUE TITLE
Add 'status' field to blood_donation collection

### ISSUE THREAD

**Issue by AntonioPavkovic** [Medic01/Sustav_za_transfuziologiju#43]
Instead of having 'accepted' or 'rejected' collections it would be better to have a field for example 'status
' in blood_donation collection which would be used for checking if the donation is accepted or not.

@jozogs the situation with our database is like this 

we have an initial collection that saves the donor name and email, blood type, users id and donation date that the user requested,

we have another collection with the same data, with additional blood donation info

two more collections 'accepted' and 'rejected' which only have accepted/rejected blood donations

will it be better if we have one collection named "donation" which will initially look like this 

`donation {
    user_id
    donor_name
    email
    date
    blood_type
    is_accepted:false
}`

when the user makes a donation the same database will look like this 

`donation {
    user_id
    donor_name
    email
    date
    blood_type
    is_accepted:false
    
    location
    blood_pressure
    hemoglobin
    doctor_name
    technician name
}`

when the doctor accepts the donation `is_accepted` field updates to `true` if he rejects the `donation` collection is updated with "rejection_reason"

**Comment by jozogs** [comment]
Fine for me!
